/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type OtpResponse,
    OtpResponseFromJSON,
    OtpResponseToJSON,
} from '../models/OtpResponse';
import {
    type OtpStatusResponse,
    OtpStatusResponseFromJSON,
    OtpStatusResponseToJSON,
} from '../models/OtpStatusResponse';
import {
    type ResendRequest,
    ResendRequestFromJSON,
    ResendRequestToJSON,
} from '../models/ResendRequest';
import {
    type SendRequest,
    SendRequestFromJSON,
    SendRequestToJSON,
} from '../models/SendRequest';
import {
    type VerifyRequest,
    VerifyRequestFromJSON,
    VerifyRequestToJSON,
} from '../models/VerifyRequest';
import {
    type VerifyResponse,
    VerifyResponseFromJSON,
    VerifyResponseToJSON,
} from '../models/VerifyResponse';

export interface GetOtpStatusRequest {
    /**
     * 
     */
    otpId: string;
}

export interface ResendOtpRequest {
    /**
     * 
     */
    resendRequest: ResendRequest;
}

export interface SendOtpRequest {
    /**
     * 
     */
    sendRequest: SendRequest;
    /**
     * Replay the prior response for a repeated request; a reused key with a different body is a 409.
     */
    idempotencyKey?: string;
}

export interface VerifyOtpRequest {
    /**
     * 
     */
    verifyRequest: VerifyRequest;
}

/**
 * 
 */
export class OTPApi extends runtime.BaseAPI {

    /**
     * Creates request options for getOtpStatus without sending the request
     */
    async getOtpStatusRequestOpts(requestParameters: GetOtpStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['otpId'] == null) {
            throw new runtime.RequiredError(
                'otpId',
                'Required parameter "otpId" was null or undefined when calling getOtpStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/otp/{otp_id}`;
        urlPath = urlPath.replace('{otp_id}', encodeURIComponent(String(requestParameters['otpId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch the current status of an OTP.
     */
    async getOtpStatusRaw(requestParameters: GetOtpStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OtpStatusResponse>> {
        const requestOptions = await this.getOtpStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OtpStatusResponseFromJSON(jsonValue));
    }

    /**
     * Fetch the current status of an OTP.
     */
    async getOtpStatus(requestParameters: GetOtpStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OtpStatusResponse> {
        const response = await this.getOtpStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resendOtp without sending the request
     */
    async resendOtpRequestOpts(requestParameters: ResendOtpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resendRequest'] == null) {
            throw new runtime.RequiredError(
                'resendRequest',
                'Required parameter "resendRequest" was null or undefined when calling resendOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/otp/resend`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResendRequestToJSON(requestParameters['resendRequest']),
        };
    }

    /**
     * Resend a pending OTP, escalating the channel if configured.
     */
    async resendOtpRaw(requestParameters: ResendOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OtpResponse>> {
        const requestOptions = await this.resendOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OtpResponseFromJSON(jsonValue));
    }

    /**
     * Resend a pending OTP, escalating the channel if configured.
     */
    async resendOtp(requestParameters: ResendOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OtpResponse> {
        const response = await this.resendOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendOtp without sending the request
     */
    async sendOtpRequestOpts(requestParameters: SendOtpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendRequest'] == null) {
            throw new runtime.RequiredError(
                'sendRequest',
                'Required parameter "sendRequest" was null or undefined when calling sendOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['idempotency-key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/otp/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendRequestToJSON(requestParameters['sendRequest']),
        };
    }

    /**
     * Routing picks the channel from the app config. When it selects WhatsApp the code is not sent yet: the response returns action_url (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. On all other channels the code is delivered directly and action_url is null. Either way the user enters the code and you call POST /otp/verify.
     * Start an OTP: routes a channel and dispatches the code.
     */
    async sendOtpRaw(requestParameters: SendOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OtpResponse>> {
        const requestOptions = await this.sendOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OtpResponseFromJSON(jsonValue));
    }

    /**
     * Routing picks the channel from the app config. When it selects WhatsApp the code is not sent yet: the response returns action_url (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. On all other channels the code is delivered directly and action_url is null. Either way the user enters the code and you call POST /otp/verify.
     * Start an OTP: routes a channel and dispatches the code.
     */
    async sendOtp(requestParameters: SendOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OtpResponse> {
        const response = await this.sendOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyOtp without sending the request
     */
    async verifyOtpRequestOpts(requestParameters: VerifyOtpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verifyRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyRequest',
                'Required parameter "verifyRequest" was null or undefined when calling verifyOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/otp/verify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyRequestToJSON(requestParameters['verifyRequest']),
        };
    }

    /**
     * Verify a code against a pending OTP.
     */
    async verifyOtpRaw(requestParameters: VerifyOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyResponse>> {
        const requestOptions = await this.verifyOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyResponseFromJSON(jsonValue));
    }

    /**
     * Verify a code against a pending OTP.
     */
    async verifyOtp(requestParameters: VerifyOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyResponse> {
        const response = await this.verifyOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
