/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type OtpResponse,
    OtpResponseFromJSON,
    OtpResponseToJSON,
} from '../models/OtpResponse';
import {
    type OtpStatusResponse,
    OtpStatusResponseFromJSON,
    OtpStatusResponseToJSON,
} from '../models/OtpStatusResponse';
import {
    type ResendRequest,
    ResendRequestFromJSON,
    ResendRequestToJSON,
} from '../models/ResendRequest';
import {
    type SendRequest,
    SendRequestFromJSON,
    SendRequestToJSON,
} from '../models/SendRequest';
import {
    type VerifyRequest,
    VerifyRequestFromJSON,
    VerifyRequestToJSON,
} from '../models/VerifyRequest';
import {
    type VerifyResponse,
    VerifyResponseFromJSON,
    VerifyResponseToJSON,
} from '../models/VerifyResponse';

export interface GetOtpStatusRequest {
    /**
     * 
     */
    otpId: string;
}

export interface ResendOtpRequest {
    /**
     * 
     */
    resendRequest: ResendRequest;
}

export interface SendOtpRequest {
    /**
     * 
     */
    sendRequest: SendRequest;
    /**
     * Replays the prior response for the same key; a reused key with a different body is a 409.
     */
    idempotencyKey?: string;
}

export interface VerifyOtpRequest {
    /**
     * 
     */
    verifyRequest: VerifyRequest;
}

/**
 * 
 */
export class OTPApi extends runtime.BaseAPI {

    /**
     * Creates request options for getOtpStatus without sending the request
     */
    async getOtpStatusRequestOpts(requestParameters: GetOtpStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['otpId'] == null) {
            throw new runtime.RequiredError(
                'otpId',
                'Required parameter "otpId" was null or undefined when calling getOtpStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/otp/{otp_id}`;
        urlPath = urlPath.replace('{otp_id}', encodeURIComponent(String(requestParameters['otpId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get OTP status
     */
    async getOtpStatusRaw(requestParameters: GetOtpStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OtpStatusResponse>> {
        const requestOptions = await this.getOtpStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OtpStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get OTP status
     */
    async getOtpStatus(requestParameters: GetOtpStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OtpStatusResponse> {
        const response = await this.getOtpStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resendOtp without sending the request
     */
    async resendOtpRequestOpts(requestParameters: ResendOtpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resendRequest'] == null) {
            throw new runtime.RequiredError(
                'resendRequest',
                'Required parameter "resendRequest" was null or undefined when calling resendOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/otp/resend`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResendRequestToJSON(requestParameters['resendRequest']),
        };
    }

    /**
     * Resend a pending OTP, advancing to the next configured channel (e.g. SMS to WhatsApp).
     * Resend an OTP
     */
    async resendOtpRaw(requestParameters: ResendOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OtpResponse>> {
        const requestOptions = await this.resendOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OtpResponseFromJSON(jsonValue));
    }

    /**
     * Resend a pending OTP, advancing to the next configured channel (e.g. SMS to WhatsApp).
     * Resend an OTP
     */
    async resendOtp(requestParameters: ResendOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OtpResponse> {
        const response = await this.resendOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendOtp without sending the request
     */
    async sendOtpRequestOpts(requestParameters: SendOtpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendRequest'] == null) {
            throw new runtime.RequiredError(
                'sendRequest',
                'Required parameter "sendRequest" was null or undefined when calling sendOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/otp/send`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendRequestToJSON(requestParameters['sendRequest']),
        };
    }

    /**
     * Generate a one-time password and deliver it to the recipient. The channel is chosen by your app\'s routing (default order + per-country overrides). Returns an `otp_id` to verify against. When routing picks WhatsApp the code is not sent yet: the response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. On every channel the user enters the code and you call `/otp/verify`. 
     * Send an OTP
     */
    async sendOtpRaw(requestParameters: SendOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OtpResponse>> {
        const requestOptions = await this.sendOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OtpResponseFromJSON(jsonValue));
    }

    /**
     * Generate a one-time password and deliver it to the recipient. The channel is chosen by your app\'s routing (default order + per-country overrides). Returns an `otp_id` to verify against. When routing picks WhatsApp the code is not sent yet: the response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. On every channel the user enters the code and you call `/otp/verify`. 
     * Send an OTP
     */
    async sendOtp(requestParameters: SendOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OtpResponse> {
        const response = await this.sendOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyOtp without sending the request
     */
    async verifyOtpRequestOpts(requestParameters: VerifyOtpRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verifyRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyRequest',
                'Required parameter "verifyRequest" was null or undefined when calling verifyOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/otp/verify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyRequestToJSON(requestParameters['verifyRequest']),
        };
    }

    /**
     * Verify the code the user entered. `matched: true` means the code was correct.
     * Verify an OTP
     */
    async verifyOtpRaw(requestParameters: VerifyOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyResponse>> {
        const requestOptions = await this.verifyOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyResponseFromJSON(jsonValue));
    }

    /**
     * Verify the code the user entered. `matched: true` means the code was correct.
     * Verify an OTP
     */
    async verifyOtp(requestParameters: VerifyOtpRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyResponse> {
        const response = await this.verifyOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
