/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type VerificationExchangeRequest,
    VerificationExchangeRequestFromJSON,
    VerificationExchangeRequestToJSON,
} from '../models/VerificationExchangeRequest';
import {
    type VerificationExchangeResponse,
    VerificationExchangeResponseFromJSON,
    VerificationExchangeResponseToJSON,
} from '../models/VerificationExchangeResponse';

export interface ExchangeVerificationRequest {
    /**
     * 
     */
    verificationExchangeRequest: VerificationExchangeRequest;
}

/**
 * 
 */
export class VerificationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for exchangeVerification without sending the request
     */
    async exchangeVerificationRequestOpts(requestParameters: ExchangeVerificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['verificationExchangeRequest'] == null) {
            throw new runtime.RequiredError(
                'verificationExchangeRequest',
                'Required parameter "verificationExchangeRequest" was null or undefined when calling exchangeVerification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/verifications/exchange`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerificationExchangeRequestToJSON(requestParameters['verificationExchangeRequest']),
        };
    }

    /**
     * Call this from YOUR backend, with a server key from your API Keys page, using the verification_token your app received from POST /client/otp/verify. It returns the recipient that was actually verified. This is the only trustworthy answer to \"did this user prove they control this number\": the `matched` field the device saw is a UI hint, read off a device you do not control, and an app can claim anything. Exchanging is idempotent for the same API key within the token lifetime, so a retry after a network failure returns the same result instead of losing the verification. Any other key, a second use, or an expired token gets a 404.
     * Exchange a verification token for the recipient it proves.
     */
    async exchangeVerificationRaw(requestParameters: ExchangeVerificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerificationExchangeResponse>> {
        const requestOptions = await this.exchangeVerificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerificationExchangeResponseFromJSON(jsonValue));
    }

    /**
     * Call this from YOUR backend, with a server key from your API Keys page, using the verification_token your app received from POST /client/otp/verify. It returns the recipient that was actually verified. This is the only trustworthy answer to \"did this user prove they control this number\": the `matched` field the device saw is a UI hint, read off a device you do not control, and an app can claim anything. Exchanging is idempotent for the same API key within the token lifetime, so a retry after a network failure returns the same result instead of losing the verification. Any other key, a second use, or an expired token gets a 404.
     * Exchange a verification token for the recipient it proves.
     */
    async exchangeVerification(requestParameters: ExchangeVerificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerificationExchangeResponse> {
        const response = await this.exchangeVerificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
