/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The channel the OTP was sent on (null before a channel is chosen).
 * @export
 */
export const Channel = {
    Sms: 'sms',
    Whatsapp: 'whatsapp',
    Email: 'email',
    Telegram: 'telegram'
} as const;
export type Channel = typeof Channel[keyof typeof Channel];


export function instanceOfChannel(value: any): boolean {
    for (const key in Channel) {
        if (Object.prototype.hasOwnProperty.call(Channel, key)) {
            if (Channel[key as keyof typeof Channel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChannelFromJSON(json: any): Channel {
    return ChannelFromJSONTyped(json, false);
}

export function ChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Channel {
    return json as Channel;
}

export function ChannelToJSON(value?: Channel | null): any {
    return value as any;
}

export function ChannelToJSONTyped(value: any, ignoreDiscriminator: boolean): Channel {
    return value as Channel;
}

