/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Channel the OTP was dispatched on; null until routed.
 * @export
 */
export const Channel = {
    Sms: 'sms',
    Whatsapp: 'whatsapp',
    Email: 'email',
    Telegram: 'telegram'
} as const;
export type Channel = typeof Channel[keyof typeof Channel];


export function instanceOfChannel(value: any): boolean {
    for (const key in Channel) {
        if (Object.prototype.hasOwnProperty.call(Channel, key)) {
            if (Channel[key as keyof typeof Channel] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ChannelFromJSON(json: any): Channel {
    return ChannelFromJSONTyped(json, false);
}

export function ChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Channel {
    return json as Channel;
}

export function ChannelToJSON(value?: Channel | null): any {
    return value as any;
}

export function ChannelToJSONTyped(value: any, ignoreDiscriminator: boolean): Channel {
    return value as Channel;
}

