/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorBody
 */
export interface ErrorBody {
    /**
     * Machine-readable error class, e.g. "OtpNotFoundError".
     */
    type: string;
    /**
     * Human-readable message. Safe to log; never contains the OTP code.
     */
    message: string;
    /**
     * Structured context, present on validation errors ({loc, msg, type} per field) and a few domain errors.
     */
    details?: { [key: string]: any; };
}

/**
 * Check if a given object implements the ErrorBody interface.
 */
export function instanceOfErrorBody(value: object): value is ErrorBody {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorBodyFromJSON(json: any): ErrorBody {
    return ErrorBodyFromJSONTyped(json, false);
}

export function ErrorBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorBody {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'message': json['message'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function ErrorBodyToJSON(json: any): ErrorBody {
    return ErrorBodyToJSONTyped(json, false);
}

export function ErrorBodyToJSONTyped(value?: ErrorBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'message': value['message'],
        'details': value['details'],
    };
}

