/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Channel } from './Channel';
import {
    ChannelFromJSON,
    ChannelFromJSONTyped,
    ChannelToJSON,
    ChannelToJSONTyped,
} from './Channel';

/**
 * 
 * @export
 * @interface OtpResponse
 */
export interface OtpResponse {
    /**
     * 
     */
    otpId: string;
    /**
     * 
     */
    status: Status;
    /**
     * Channel the OTP was dispatched on; null until routed.
     */
    channel: Channel | null;
    /**
     * Recipient with the middle digits masked.
     */
    maskedRecipient: string;
    /**
     * WhatsApp link the user opens to receive the code: they send us the prefilled message and we reply with the code over WhatsApp, then they enter it and you call POST /otp/verify. Present only when dispatched on the whatsapp channel; null otherwise.
     */
    actionUrl?: string | null;
}



/**
 * Check if a given object implements the OtpResponse interface.
 */
export function instanceOfOtpResponse(value: object): value is OtpResponse {
    if ((!('otpId' in (value as Record<string, any>)) && !('otp_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['otpId'] === undefined && (value as Record<string, any>)['otp_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if ((!('maskedRecipient' in (value as Record<string, any>)) && !('masked_recipient' in (value as Record<string, any>))) || ((value as Record<string, any>)['maskedRecipient'] === undefined && (value as Record<string, any>)['masked_recipient'] === undefined)) return false;
    return true;
}

export function OtpResponseFromJSON(json: any): OtpResponse {
    return OtpResponseFromJSONTyped(json, false);
}

export function OtpResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtpResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'otpId': json['otp_id'],
        'status': StatusFromJSON(json['status']),
        'channel': ChannelFromJSON(json['channel']),
        'maskedRecipient': json['masked_recipient'],
        'actionUrl': json['action_url'] === undefined ? undefined : json['action_url'] === null ? null : json['action_url'],
    };
}

export function OtpResponseToJSON(json: any): OtpResponse {
    return OtpResponseToJSONTyped(json, false);
}

export function OtpResponseToJSONTyped(value?: OtpResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp_id': value['otpId'],
        'status': StatusToJSON(value['status']),
        'channel': ChannelToJSON(value['channel']),
        'masked_recipient': value['maskedRecipient'],
        'action_url': value['actionUrl'],
    };
}

