/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface OtpStatusResponse
 */
export interface OtpStatusResponse {
    /**
     * 
     */
    otpId: string;
    /**
     * 
     */
    status: Status;
    /**
     * Recipient with the middle digits masked.
     */
    maskedRecipient: string;
}



/**
 * Check if a given object implements the OtpStatusResponse interface.
 */
export function instanceOfOtpStatusResponse(value: object): value is OtpStatusResponse {
    if ((!('otpId' in (value as Record<string, any>)) && !('otp_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['otpId'] === undefined && (value as Record<string, any>)['otp_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('maskedRecipient' in (value as Record<string, any>)) && !('masked_recipient' in (value as Record<string, any>))) || ((value as Record<string, any>)['maskedRecipient'] === undefined && (value as Record<string, any>)['masked_recipient'] === undefined)) return false;
    return true;
}

export function OtpStatusResponseFromJSON(json: any): OtpStatusResponse {
    return OtpStatusResponseFromJSONTyped(json, false);
}

export function OtpStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OtpStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'otpId': json['otp_id'],
        'status': StatusFromJSON(json['status']),
        'maskedRecipient': json['masked_recipient'],
    };
}

export function OtpStatusResponseToJSON(json: any): OtpStatusResponse {
    return OtpStatusResponseToJSONTyped(json, false);
}

export function OtpStatusResponseToJSONTyped(value?: OtpStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp_id': value['otpId'],
        'status': StatusToJSON(value['status']),
        'masked_recipient': value['maskedRecipient'],
    };
}

