/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RecipientType = {
    Phone: 'phone',
    Email: 'email'
} as const;
export type RecipientType = typeof RecipientType[keyof typeof RecipientType];


export function instanceOfRecipientType(value: any): boolean {
    for (const key in RecipientType) {
        if (Object.prototype.hasOwnProperty.call(RecipientType, key)) {
            if (RecipientType[key as keyof typeof RecipientType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RecipientTypeFromJSON(json: any): RecipientType {
    return RecipientTypeFromJSONTyped(json, false);
}

export function RecipientTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipientType {
    return json as RecipientType;
}

export function RecipientTypeToJSON(value?: RecipientType | null): any {
    return value as any;
}

export function RecipientTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): RecipientType {
    return value as RecipientType;
}

