/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendRequest
 */
export interface ResendRequest {
    /**
     * 
     */
    otpId: string;
    /**
     * Move this OTP onto a specific channel, e.g. "sms" when the recipient has no WhatsApp. The channel must be enabled for your app and the recipient. Omit to advance to the next channel in your routing order.
     * 
     */
    channel?: ResendRequestChannelEnum | null;
}


/**
 * @export
 */
export const ResendRequestChannelEnum = {
    Sms: 'sms',
    Whatsapp: 'whatsapp',
    Email: 'email',
    Telegram: 'telegram'
} as const;
export type ResendRequestChannelEnum = typeof ResendRequestChannelEnum[keyof typeof ResendRequestChannelEnum];


/**
 * Check if a given object implements the ResendRequest interface.
 */
export function instanceOfResendRequest(value: object): value is ResendRequest {
    if ((!('otpId' in (value as Record<string, any>)) && !('otp_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['otpId'] === undefined && (value as Record<string, any>)['otp_id'] === undefined)) return false;
    return true;
}

export function ResendRequestFromJSON(json: any): ResendRequest {
    return ResendRequestFromJSONTyped(json, false);
}

export function ResendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'otpId': json['otp_id'],
        'channel': json['channel'] === undefined ? undefined : json['channel'] === null ? null : json['channel'],
    };
}

export function ResendRequestToJSON(json: any): ResendRequest {
    return ResendRequestToJSONTyped(json, false);
}

export function ResendRequestToJSONTyped(value?: ResendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp_id': value['otpId'],
        'channel': value['channel'],
    };
}

