/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Channel } from './Channel';
import {
    ChannelFromJSON,
    ChannelFromJSONTyped,
    ChannelToJSON,
    ChannelToJSONTyped,
} from './Channel';

/**
 * 
 * @export
 * @interface ResendRequest
 */
export interface ResendRequest {
    /**
     * The OTP id to resend.
     */
    otpId: string;
    /**
     * Move this OTP onto a specific channel, e.g. "sms" when the recipient has no WhatsApp. The channel must be enabled for your app and the recipient. Omit to advance to the next channel in your routing order.
     */
    channel?: Channel | null;
}



/**
 * Check if a given object implements the ResendRequest interface.
 */
export function instanceOfResendRequest(value: object): value is ResendRequest {
    if ((!('otpId' in (value as Record<string, any>)) && !('otp_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['otpId'] === undefined && (value as Record<string, any>)['otp_id'] === undefined)) return false;
    return true;
}

export function ResendRequestFromJSON(json: any): ResendRequest {
    return ResendRequestFromJSONTyped(json, false);
}

export function ResendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'otpId': json['otp_id'],
        'channel': json['channel'] === undefined ? undefined : json['channel'] === null ? null : ChannelFromJSON(json['channel']),
    };
}

export function ResendRequestToJSON(json: any): ResendRequest {
    return ResendRequestToJSONTyped(json, false);
}

export function ResendRequestToJSONTyped(value?: ResendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp_id': value['otpId'],
        'channel': ChannelToJSON(value['channel']),
    };
}

