/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendRequest
 */
export interface SendRequest {
    /**
     * Phone number in E.164 (e.g. +14155552671) or an email address.
     */
    recipient: string;
    /**
     * Message language, e.g. "en" or "tr".
     */
    locale?: string;
}

/**
 * Check if a given object implements the SendRequest interface.
 */
export function instanceOfSendRequest(value: object): value is SendRequest {
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    return true;
}

export function SendRequestFromJSON(json: any): SendRequest {
    return SendRequestFromJSONTyped(json, false);
}

export function SendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipient': json['recipient'],
        'locale': json['locale'] == null ? undefined : json['locale'],
    };
}

export function SendRequestToJSON(json: any): SendRequest {
    return SendRequestToJSONTyped(json, false);
}

export function SendRequestToJSONTyped(value?: SendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipient': value['recipient'],
        'locale': value['locale'],
    };
}

