/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendRequest
 */
export interface SendRequest {
    /**
     * Phone number (E.164) or email address to deliver the OTP to.
     */
    recipient: string;
    /**
     * BCP-47 locale for the message template; falls back to the app default.
     */
    locale?: string | null;
    /**
     * IP address of the end user who triggered this OTP (IPv4 or IPv6). Strongly recommended: requests without it share a much tighter per-app rate limit, and it feeds abuse protection for your own traffic. Private/reserved addresses count as absent.
     */
    clientIp?: string | null;
}

/**
 * Check if a given object implements the SendRequest interface.
 */
export function instanceOfSendRequest(value: object): value is SendRequest {
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    return true;
}

export function SendRequestFromJSON(json: any): SendRequest {
    return SendRequestFromJSONTyped(json, false);
}

export function SendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipient': json['recipient'],
        'locale': json['locale'] === undefined ? undefined : json['locale'] === null ? null : json['locale'],
        'clientIp': json['client_ip'] === undefined ? undefined : json['client_ip'] === null ? null : json['client_ip'],
    };
}

export function SendRequestToJSON(json: any): SendRequest {
    return SendRequestToJSONTyped(json, false);
}

export function SendRequestToJSONTyped(value?: SendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipient': value['recipient'],
        'locale': value['locale'],
        'client_ip': value['clientIp'],
    };
}

