/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';

/**
 * 
 * @export
 * @interface VerifyResponse
 */
export interface VerifyResponse {
    /**
     * 
     */
    otpId: string;
    /**
     * 
     */
    status: Status;
    /**
     * 
     */
    matched: boolean;
}



/**
 * Check if a given object implements the VerifyResponse interface.
 */
export function instanceOfVerifyResponse(value: object): value is VerifyResponse {
    if ((!('otpId' in (value as Record<string, any>)) && !('otp_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['otpId'] === undefined && (value as Record<string, any>)['otp_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('matched' in value) || value['matched'] === undefined) return false;
    return true;
}

export function VerifyResponseFromJSON(json: any): VerifyResponse {
    return VerifyResponseFromJSONTyped(json, false);
}

export function VerifyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'otpId': json['otp_id'],
        'status': StatusFromJSON(json['status']),
        'matched': json['matched'],
    };
}

export function VerifyResponseToJSON(json: any): VerifyResponse {
    return VerifyResponseToJSONTyped(json, false);
}

export function VerifyResponseToJSONTyped(value?: VerifyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp_id': value['otpId'],
        'status': StatusToJSON(value['status']),
        'matched': value['matched'],
    };
}

