/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyRequest
 */
export interface VerifyRequest {
    /**
     * 
     */
    otpId: string;
    /**
     * 
     */
    code: string;
}

/**
 * Check if a given object implements the VerifyRequest interface.
 */
export function instanceOfVerifyRequest(value: object): value is VerifyRequest {
    if ((!('otpId' in (value as Record<string, any>)) && !('otp_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['otpId'] === undefined && (value as Record<string, any>)['otp_id'] === undefined)) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function VerifyRequestFromJSON(json: any): VerifyRequest {
    return VerifyRequestFromJSONTyped(json, false);
}

export function VerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'otpId': json['otp_id'],
        'code': json['code'],
    };
}

export function VerifyRequestToJSON(json: any): VerifyRequest {
    return VerifyRequestToJSONTyped(json, false);
}

export function VerifyRequestToJSONTyped(value?: VerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp_id': value['otpId'],
        'code': value['code'],
    };
}

