/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerificationExchangeRequest
 */
export interface VerificationExchangeRequest {
    /**
     * The verification_token your app received from POST /client/otp/verify.
     */
    verificationToken: string;
}

/**
 * Check if a given object implements the VerificationExchangeRequest interface.
 */
export function instanceOfVerificationExchangeRequest(value: object): value is VerificationExchangeRequest {
    if ((!('verificationToken' in (value as Record<string, any>)) && !('verification_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['verificationToken'] === undefined && (value as Record<string, any>)['verification_token'] === undefined)) return false;
    return true;
}

export function VerificationExchangeRequestFromJSON(json: any): VerificationExchangeRequest {
    return VerificationExchangeRequestFromJSONTyped(json, false);
}

export function VerificationExchangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationExchangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'verificationToken': json['verification_token'],
    };
}

export function VerificationExchangeRequestToJSON(json: any): VerificationExchangeRequest {
    return VerificationExchangeRequestToJSONTyped(json, false);
}

export function VerificationExchangeRequestToJSONTyped(value?: VerificationExchangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verification_token': value['verificationToken'],
    };
}

