/* tslint:disable */
/* eslint-disable */
/**
 * otp OTP API
 * Public API for sending and verifying one-time passwords. Authenticate every request with your API key as a Bearer token. The delivery channel is chosen by your account routing; you only pass the recipient. The code itself is never returned by the API.  Errors are always `{\"error\": {\"type\", \"message\", \"details\"?}}`.  When routing picks WhatsApp the code is not sent yet: the send response carries an `action_url` (a wa.me link) the user opens to receive the code over WhatsApp, and the OTP stays pending until they enter it. Verification is identical on every channel.  If your app uses one of the mobile SDKs, the device verifies against the client API and receives a `verification_token` instead of a result. Exchange that token here, with your server key (`POST /verifications/exchange`), to learn which recipient was verified. What an app tells your backend about its own verification is unverifiable, so the token is the whole security model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Channel } from './Channel';
import {
    ChannelFromJSON,
    ChannelFromJSONTyped,
    ChannelToJSON,
    ChannelToJSONTyped,
} from './Channel';
import type { RecipientType } from './RecipientType';
import {
    RecipientTypeFromJSON,
    RecipientTypeFromJSONTyped,
    RecipientTypeToJSON,
    RecipientTypeToJSONTyped,
} from './RecipientType';

/**
 * 
 * @export
 * @interface VerificationExchangeResponse
 */
export interface VerificationExchangeResponse {
    /**
     * The OTP this verification belongs to.
     */
    otpId: string;
    /**
     * The recipient that was verified, in full. This is the answer the device could not be trusted to give you.
     */
    recipient: string;
    /**
     * 
     */
    recipientType: RecipientType;
    /**
     * Channel the verified code was delivered on.
     */
    channel: Channel | null;
    /**
     * When the end user entered the correct code.
     */
    verifiedAt: Date;
}



/**
 * Check if a given object implements the VerificationExchangeResponse interface.
 */
export function instanceOfVerificationExchangeResponse(value: object): value is VerificationExchangeResponse {
    if ((!('otpId' in (value as Record<string, any>)) && !('otp_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['otpId'] === undefined && (value as Record<string, any>)['otp_id'] === undefined)) return false;
    if (!('recipient' in value) || value['recipient'] === undefined) return false;
    if ((!('recipientType' in (value as Record<string, any>)) && !('recipient_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['recipientType'] === undefined && (value as Record<string, any>)['recipient_type'] === undefined)) return false;
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if ((!('verifiedAt' in (value as Record<string, any>)) && !('verified_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['verifiedAt'] === undefined && (value as Record<string, any>)['verified_at'] === undefined)) return false;
    return true;
}

export function VerificationExchangeResponseFromJSON(json: any): VerificationExchangeResponse {
    return VerificationExchangeResponseFromJSONTyped(json, false);
}

export function VerificationExchangeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerificationExchangeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'otpId': json['otp_id'],
        'recipient': json['recipient'],
        'recipientType': RecipientTypeFromJSON(json['recipient_type']),
        'channel': ChannelFromJSON(json['channel']),
        'verifiedAt': (new Date(json['verified_at'])),
    };
}

export function VerificationExchangeResponseToJSON(json: any): VerificationExchangeResponse {
    return VerificationExchangeResponseToJSONTyped(json, false);
}

export function VerificationExchangeResponseToJSONTyped(value?: VerificationExchangeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'otp_id': value['otpId'],
        'recipient': value['recipient'],
        'recipient_type': RecipientTypeToJSON(value['recipientType']),
        'channel': ChannelToJSON(value['channel']),
        'verified_at': value['verifiedAt'].toISOString(),
    };
}

